id = "qb-woodland-theme"
name = "Woodland Theme"
version = "0.0.1"
schema_version = 1
authors = ["qb-bbq-bq"]
description = "A brown-based theme with green accents and light pink cursor"
repository = "https://github.com/qb-bbq-bq/zed-woodland-theme"
